* Introduction

In this document I describe my way of working (installing & updating) with NixOS, which is the result of many
iterations. The goal of my configuration is to create setup which allows me to define all my devices.

Currently I only use flakes in a modular fashion and I have dropped home-manager because I like to change and test my
configurations on the fly without the need to rebuild my entire system!

Which means that most applications are configured via their dotfiles, and I've left the management of my .dotfiles out
of Nix entirely and opted to work with a dotfile manager. Since I work on different OS'es throughout the day this has
the added benefit that I can reuse my dotfiles across all the operating systems I use.

The dotfile manager I'm currently using is [[https://www.chezmoi.io/][chezmoi]].

If you want to learn more about NixOS and the way you can install & configure it, I can recommend the following
resource: [[https://nixos.wiki/wiki/Wil_T_Nix_Guides][Will T Nix Guides]]  by Will Taylor,  and you should also read the NixOS Installation Guide:
https://nixos.wiki/wiki/NixOS_Installation_Guide

* Installing NixOS (clean install)

I tend to install new pc's with the bare minimum config (and some sensible defaults) I need. 
And once I've booted into the persisted system, I apply the config I want. This approach allows
me to rollback to a working version.

_Summary steps:_
1. Create your installation medium;
2. After booting into the installer, I launch a partition editor and partition my drives;
3. I mount the necessary partitions as =/mnt= and =/mnt/boot= (according to the NixOS installation manual;
4. I run =sudo nixos-generate-config --root .mnt= which creates 2 files: config & hardware config;
5. I edit these file to configure some basic/sensible defaults, like:
   - creating a user
   - setting a hostname
   - have some default applications like: browser, text editor
6. Once done and save, I run =sudo nixs-install --root /mnt= and wait;
7. Reboot into my new system and migrate my config to flakes;

Working this way means I have to apply my personal config later, but it gives me that first persistent generation
to fallback on sice otherwise I'd have to redo the entire thing all over again.


** Step 1 - Prepare installation medium

Download one of the [[https://nixos.org/download.html][NixOS iso images]] from the NixOS website, I tend to favour the (non-graphical) =minimal ISO image=.

Next I'll prepare a usb flash drive with Ventoy and copy the NixOS iso image onto it. And after that you can boot up the
NixOS installer.

Before you boot the installer, make sure you have:
- Disabled Secure Boot Control
- Disabled USB legacy boot

** Step 2 - Partitioning

After booting the installer, the first thing you need to do is to identify what type of firmware your computer uses:
either UEFI or legacy BIOS and then choose the appropriate partioning scheme for that firmware.

In Linux (and in the NixOS shell) you can use the following command to find out which one you are using:

#+begin_src
$ [ -d /sys/firmware/efi ] && echo UEFI || echo BIOS
#+end_src

Create at least 2 partitions one boot partition and one root partition, the boot partition will either be an ext4
partition (legacy BIOS) or a ESP/fat partition (UEFI) whereas the root partition will be a LVM (8300 Linux LVM)
partition (which we can encrypt for additional security).

Since mosts computers use UEFI nowadays I'll write out the partitioning setup for a UEFI system.

Create a 500mb EFI boot partition (=/dev/sda1=) and the rest will be our nd the rest will be our LUKS encrypted physical
volume for LVM (=/dev/sda2=).

#+begin_src
$ gdisk /dev/sda
#+end_src

- =o= (create new empty partition table)
- =n= (add partition, 500M, type ef00 EFI)
- =n= (add partition, remaining space, type 8300 Linux LVM)
- =w= (write partition table and exit)

Setup the encrypted LUKS partition and open it:

#+begin_src
$  cryptsetup luksFormat /dev/sda2  #encrypt the partition with luks
$  cryptsetup luksOpen /dev/sda2 enc-pv # decrypt the partition to a device name sda2-enc
#+end_src

Now we are ready to add our encrypted volume to LVM:

#+begin_src
$ pvcreate /dev/mapper/sda2-enc # add our encrypted partition as physical volume to LVM
$ vgcreate vg-nixos /dev/mapper/sda2-enc # add the physical volume to volumegroup vg-nixos
$ lvcreate -L 8G -n lv-swap vg-nixos # setup a logical volume (8GB size) for swap purposes in vg-nixos
$ lvcreate -l '100%FREE' -n lv-root vg-nixos # create a logical volume for your root (remaing size) in vg-nixos
#+end_src

Format the swap and root partitions (and label them!):

#+begin_src
$ mkswap -L swap /dev/vg-nixos/lv-swap
$ mkfs.ext4 -L root /dev/vg-nixos/lv-root 
#+end_src

** Step 3 - Install NixOS

We mount the partitions we just created under =/mnt= so we can install NixOS on them.

#+begin_src
$ mount /dev/vg_nixos/lv_root /mnt
$ mkdir /mnt/boot
$ mount /dev/sda1 /mnt/boot
$ swapon /dev/vg_nixos/lv_swap
#+end_src

Configure WPA supplicant so we can use WIFI:

#+begin_src
$ cat > /etc/wpa_supplicant.conf
network={
  ssid="****"
  psk="****"
}
^D
$ systemctl start wpa_supplicant
#+end_src


** Easy initial configuration

NixOS provides good support for the Xfce desktop environment out-of-the-box, but the defaults are minimal. The files in
the default folder provide  a more complete experience, including a suite of basic software and plugins.

You can change the generated configuration.nix file by including the desired .nix files from the =defaults= folder.
The nix.nix file under the defaults folder is for instance already setup to enable flakes support.

#+begin_example
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./defaults/nix.nix
    ./defaults/xfce.nix
  ];

  # the rest of your nixos configuration
}
#+end_example


** Managing the configuration with Git
:properties:
:link: https://nixos-and-flakes.thiscute.world/nixos-with-flakes/other-useful-tips
:end:

NixOS configuration, being a set of text files, is well-suited for version control with Git. This allows easy rollback
to a previous version in case of issues. 

By default, NixOS places the configuration in =/etc/nixos=, which requires root permissions for modification, making it
inconvenient for daily use. Thankfully, Flakes can help solve this problem by allowing you to place your flake anywhere
you prefer. 

For example, you can place your flake in ~/nixos-config and create a symbolic link in /etc/nixos as follows:

#+begin_src shell
sudo mv /etc/nixos /etc/nixos.bak  # Backup the original configuration
sudo ln -s ~/nixos-config /etc/nixos

# Deploy the flake.nix located at the default location (/etc/nixos)
sudo nixos-rebuild switch
#+end_src

* Maintaining your system

** Update your system
Make the necessary changes to your modules and execute:

#+begin_src shell
host-rebuild.sh
#+end_sr

** Clean up your system
You can configure NixOS to automatically clean up your system, see the section about storage optimization for more info.

*** Delete old generations

First, list all generations:

#+begin_src shell
   sudo nix-env --list-generations
   # or following command does not work the use profile options
   sudo nix-env --list-generations --profile /nix/var/nix/profiles/system  
#+end_src

To remove the unused generations, you run the =nix-env= command for specific profile with the =delete-generations= option.
The =delete-generations= option accept and ID as an argument. In this argument, you pass one or multiple IDs to delete
the old generations in NixOS:

#+begin_src shell
  sudo nix-env --delete-generations 10 
  # or
  sudo nix-env --delete-generations 10 11 12 13 14 15 16 17 18 19 20 21

  # or following command does not work the use profile options

  sudo nix-env --profile /nix/var/nix/profiles/system --delete-generations 10 
  # or 
  sudo nix-env --profile /nix/var/nix/profiles/system --delete-generations 10 11 12 13 14 15 16 17 18 19 20 21  
#+end_src

Afterwards don’t forget to run the garbage collector:

#+begin_src shell
  sudo nix-store --gc 
#+end_src

There is also a convenient little utility called =nix-collect-garbage= which when invoked with the -d (–delete-old)
switch deletes all old generations of all profiles in /nix/var/nix/profiles. So:

#+begin_src shell
  sudo nix-collect-garbage -d
#+end_src

is a quick and easy way to clean up your system.

*** Remove obsolete boot entries

First, run the garbage collection for your system, the rebuild the bootloader.

Run the garbage collector:
#+begin_src shell
  # remove everything older than 14 days
  sudo nix-collect-garbage --delete-older-than 14d
  # or remove all old generations (everything but the current generation)
  sudo nix-collect-garbage -d
#+end_src

Rebuild the bootloader:

#+begin_src shell
   sudo nixos-rebuild boot --flake . 
#+end_src

* Appendix

** Encrypted partitions

If you want to encrypt multiple partitions, it is good to know that upon booting the decryption password for the first
partition will also be used for decrypting all subsequent partitions. Which means that if you want to enter only one
password for decryption you’ll need to encrypt all partitions with the same password.

You can either choose to encrypt the partitions (or drives) first and them use those as physical volumes for LVM (LUKS +
LVM or LVM on top of LUKS) or you can set up LVM first and encrypt the logical volums with LUKS later (LVM + LUKS or
LUKS on top of LVM). I prefer to use LUKS + LVM.

** Using Flakes

*** Enabling Flakes Support for NixOS
:properties:
:link: https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-with-flakes-enabled
:end:

Currently, Flakes is still an experimental feature and not enabled by default. We need to manually modify the
/etc/nixos/configuration.nix file to enable the Flakes feature and the accompanying new nix command-line tool: 

#+begin_example
{ config, pkgs, ... }:

{
  imports = [
    # Include the results of the hardware scan.
    ./hardware-configuration.nix
  ];

  # ......

  # Enable the Flakes feature and the accompanying new nix command-line tool
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  environment.systemPackages = with pkgs; [
    # Flakes clones its dependencies through the git command,
    # so git must be installed first
    git
    vim
    wget
  ];
  # Set the default editor to vim
  environment.variables.EDITOR = "vim";

  # ......
}
#+end_example


After making these changes, run =sudo nixos-rebuild switch= to apply the modifications. Then, you can use the Flakes
feature to manage your system configuration. 

The new nix command-line tool also offers some convenient features. For example, you can now use the =nix repl= command
to open a nix interactive environment. If you're interested, you can use it to review and test all the Nix syntax you've
learned before. 

*** Switching System Configuration to =flake.nix=
:properties:
:link: https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-with-flakes-enabled
:end:

To be written out!



