#+title: NIXOS CONFIG README
#+author: Rob Kiggen

* Introduction
:properties:
:link: https://github.com/MatthiasBenaets/nixos-config
:link: https://github.com/chris-martin/home
:link: https://www.foodogsquared.one/posts/2023-03-05-combining-traditional-dotfiles-and-nixos-configurations-with-nix-flakes/
:link: https://nixos-and-flakes.thiscute.world/
:link: https://typeclasses.substack.com/p/flakes-nixos-desktop  
:end:

The goal of my current NixOS configuration is to create a multi machine / multi user setup where a single user X can
have different profiles across multiple machines.

If you want to learn more about NixOS and the way you can install & configure it, I can recommend the following resources:
- [[https://benaets.com/posts/nixos/][Getting Started with NixOS]] by Mathias Benaets
- [[https://nixos.wiki/wiki/Wil_T_Nix_Guides][Will T Nix Guides]] by Will Taylor

  
* NixOS Installation Guide

Basically the steps are the following:
1. download one of the [[https://nixos.org/download.html][NixOS iso images]] from the NixOS website;
2. burn the iso to a bootable USB flash drive (or copy it to a flash drive prepared with [[https://www.ventoy.net/en/index.html][Ventoy]]);
3. boot the installation media;
4. partition the drives from your computer (make sure to verify whether your computer supports UEFI boot or only legacy BIOS boot, and don't forget to label the partitions);
5. generate the NixOS config;
6. install NixOS;

Guides:
- [[https://nixos.org/manual/nixos/stable/#ch-installation][NixOS official installation manual]]
- [[https://nixos.wiki/wiki/NixOS_Installation_Guide][NixOS companion guide to the official installation manual]]
  
** Preparation

Prepare a usb flash drive with Ventoy and copy the NixOS iso image onto it, now you can boot up the NixOS installer.

** Partitioning

First identify whether your computer uses UEFI or legacy BIOS for booting and then choose the appropriate partioning scheme.

*** Encryption

https://gist.github.com/martijnvermaat/76f2e24d0239470dd71050358b4d5134

If you want to encrypt multiple partitions, it is good to know that upon booting the decryption password for the first partition will also be used for decrypting al subsequent passwords.
Which means that if you want to enter only one password for decryption you'll need to encrypt all partitions with the same password.

You can either choose to encrypt the partitions first and them use those as physical volumes for LVM (LUKS + LVM or LVM on top of LUKS) or you can set up LVM first and encrypt the logical volums with LUKS later (LVM + LUKS or LUKS on top of LVM). I prefer to use LUKS + LVM.


* Todo

- include maintenance commands;
