# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE: hand-extended below the auto-generated section for this specific
# machine (Framework 16, AMD 7040 series, WD_BLACK SN770 2TB NVMe).
#
# History (kept for context in case symptoms ever return):
# This machine suffered a mix of suspend/resume freezes, NVMe controller
# drops (`nvme nvme0: controller is down; will reset: CSTS=0xffffffff`),
# and a separate known upstream amdgpu/DCN3.1 display-core bug
# (dcn31_program_compbuf_size REG_WAIT timeout on display sleep -
# see https://bugzilla.kernel.org/show_bug.cgi?id=200531, confirmed by
# other Framework 16 users on the same PCI address 0000:c1:00.0).
# A long list of kernel parameters (nvme_core.default_ps_max_latency_us,
# pcie_aspm=off, pcie_port_pm=off, amdgpu.runpm=0, amdgpu.dcdebugmask,
# iommu=pt) plus a manual setpci ASPM override and a resume-time NVMe
# reset were tried as workarounds.
#
# The actual fix turned out to be much simpler:
#   1. Reset BIOS to optimal/default settings (F2 at boot)
#   2. Keep only `mem_sleep_default=s2idle` as a kernel parameter
# This configuration has since survived repeated manual `systemctl
# suspend` cycles, real-world lid-close suspend, and extended
# screensaver/idle sessions without any recurrence.
#
# If problems ever return, the diagnostic trail above (ASPM state via
# `lspci -vvv -s <nvme-pci-addr> | grep LnkCtl`, NVMe SMART health via
# `nvme smart-log`, and the amdgpu bug link) is the place to pick back up.

{ inputs, config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
      (modulesPath + "/installer/scan/not-detected.nix")
      inputs.nixos-hardware.nixosModules.framework-16-7040-amd 
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Use suspend-to-idle, the AMD platform's primary validated sleep mode.
  # This, combined with BIOS optimal/default settings, is what actually
  # fixed suspend/resume reliability on this machine - see history note
  # above.
  boot.kernelParams = [
    "mem_sleep_default=s2idle"
    "amdgpu.dcdebugmask=0x12" # Disable PSR, PSR-SU and PR
  ];  
  boot.extraModulePackages = [ ];

  # Optional: uncomment to deauthorize the Goodix fingerprint reader.
  # Investigated as a possible cause of USB reset-loop noise during
  # idle/lock cycles; turned out to be an unrelated, harmless
  # coincidence. Left here in case it's ever worth revisiting.
  # services.udev.extraRules = ''
  #     SUBSYSTEM=="usb", ATTR{idVendor}=="27c6", ATTR{idProduct}=="609c", ATTR{authorized}="0"
  # '';

  # Unencrypt LUKS partition
  boot.initrd.luks.devices."nvme0n1p2-enc" = {
      name = "nvme0n1p2-enc";
      device = "/dev/disk/by-uuid/a7355cfa-53aa-4b8f-a013-7b707cb5862b";
      preLVM = true;
      allowDiscards = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp193s0f3u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # https://wiki.archlinux.org/title/Framework_Laptop_13#WiFi/Bluetooth
  hardware.wirelessRegulatoryDatabase = true;
  hardware.enableRedistributableFirmware = true;
  hardware.keyboard.qmk.enable = true;
  hardware.bluetooth.enable = true;

}
